Repository endless-horses/oot-was, pull requests merged in 2024-01, with the labels that each got.

#2 템플릿 작성 close #1
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/resources/temp.md
Labels: documentation

#6 fix: develop 브랜치 복구 close #5
  .DS_Store
  src/main/java/com/endlesshorses/oot/OotApplication.java
  src/main/java/com/endlesshorses/oot/custom/pattern/PatternEntity.java
  src/main/java/com/endlesshorses/oot/custom/result/ResultEntity.java
  src/main/java/com/endlesshorses/oot/custom/wheel/WheelEntity.java
  src/main/java/com/endlesshorses/oot/domain/Accessory.java
  src/main/java/com/endlesshorses/oot/domain/Color.java
  src/main/java/com/endlesshorses/oot/domain/Font.java
Labels: fix

#7 pattern, wheel entity 생성 #3
  src/main/java/com/endlesshorses/oot/custom/accessory/enity/Accessory.java
  src/main/java/com/endlesshorses/oot/custom/color/entity/Color.java
  src/main/java/com/endlesshorses/oot/custom/font/entity/Font.java
  src/main/java/com/endlesshorses/oot/custom/pattern/entity/Pattern.java
  src/main/java/com/endlesshorses/oot/custom/wheel/entity/Wheel.java
  src/main/java/com/endlesshorses/oot/domain/Accessory.java
  src/main/java/com/endlesshorses/oot/domain/Color.java
  src/main/java/com/endlesshorses/oot/domain/Font.java
Labels: feature

#8 Result entity 생성 close #3
  src/main/java/com/endlesshorses/oot/custom/accessory/enity/Accessory.java
  src/main/java/com/endlesshorses/oot/custom/color/entity/Color.java
  src/main/java/com/endlesshorses/oot/custom/font/entity/Font.java
  src/main/java/com/endlesshorses/oot/custom/pattern/entity/Pattern.java
  src/main/java/com/endlesshorses/oot/custom/result/entity/Result.java
  src/main/java/com/endlesshorses/oot/custom/resultAccessory/entity/ResultAccessory.java
  src/main/java/com/endlesshorses/oot/custom/wheel/entity/Wheel.java
Labels: feature

#10 feat: swagger 구현#9 close #9
  build.gradle
  src/main/java/com/endlesshorses/oot/swagger/SwaggerConfig.java
Labels: feature

#18 CI/CD 파이프라인 구현 close #12
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
Labels: deploy

#27 패턴 목록 조회 api 구현 close #23
  src/main/java/com/endlesshorses/oot/custom/pattern/controller/PatternController.java
  src/main/java/com/endlesshorses/oot/custom/pattern/dto/PatternListResponseDto.java
  src/main/java/com/endlesshorses/oot/custom/pattern/repository/PatternRepository.java
  src/main/java/com/endlesshorses/oot/custom/pattern/service/PatternService.java
Labels: feature

#28 폰트 목록 조회 API 구현 close #22
  src/main/java/com/endlesshorses/oot/custom/font/controller/FontController.java
  src/main/java/com/endlesshorses/oot/custom/font/dto/FontListResponseDto.java
  src/main/java/com/endlesshorses/oot/custom/font/repository/FontRepository.java
  src/main/java/com/endlesshorses/oot/custom/font/service/FontService.java
Labels: feature

#26 타이어 휠 모양 목록 조회 API 구현 close #24
  src/main/java/com/endlesshorses/oot/custom/wheel/controller/WheelController.java
  src/main/java/com/endlesshorses/oot/custom/wheel/dto/WheelListResponseDto.java
  src/main/java/com/endlesshorses/oot/custom/wheel/repository/WheelRepository.java
  src/main/java/com/endlesshorses/oot/custom/wheel/service/WheelService.java
Labels: feature

#29 타이어 액세서리 목록 조회 API 구현 close #25
  src/main/java/com/endlesshorses/oot/custom/accessory/controller/AccessoryController.java
  src/main/java/com/endlesshorses/oot/custom/accessory/dto/AccessoryListResponseDto.java
  src/main/java/com/endlesshorses/oot/custom/accessory/repository/AccessoryRepository.java
  src/main/java/com/endlesshorses/oot/custom/accessory/service/AccessoryService.java
Labels: feature

#34 *ListResponseDto에 id 값 추가 close #33
  src/main/java/com/endlesshorses/oot/custom/accessory/dto/AccessoryListResponseDto.java
  src/main/java/com/endlesshorses/oot/custom/color/dto/ColorListResponseDto.java
  src/main/java/com/endlesshorses/oot/custom/font/dto/FontListResponseDto.java
  src/main/java/com/endlesshorses/oot/custom/pattern/dto/PatternListResponseDto.java
  src/main/java/com/endlesshorses/oot/custom/wheel/dto/WheelListResponseDto.java
Labels: fix

#37 CORS 설정 close #11
  src/main/java/com/endlesshorses/oot/custom/config/CorsFilter.java
Labels: feature

#39 CORS Origin 설정
  src/main/java/com/endlesshorses/oot/custom/config/CorsConfig.java
  src/main/java/com/endlesshorses/oot/custom/config/CorsFilter.java
Labels: bug, fix
